# Pytorch math functions 
#### source: https://pytorch.org/docs/stable/torch.html#math-operations
Ricardo Flores


In [1]:
import torch 

## (1) Reduction 

In [2]:
xt = torch.randn(100)  # normal, 0 mean, 1 std

In [3]:
# Mean
xt.mean()

tensor(0.0088)

In [4]:
# Standard deviation
xt.std()

tensor(1.0170)

## (2) Comparison

In [5]:
# Equal: True if two tensors have the same size and elements, False otherwise.
torch.equal(torch.tensor([9, 2]), torch.tensor([9, 2]))

True

In [6]:
# Max
torch.max(torch.tensor([1, 2, 3, 4, 5]))

tensor(5)

In [7]:
# Min
torch.min(torch.tensor([1, 2, 3, 4, 5]))

tensor(1)

## (3) Serialization 

In [8]:
# save 
xt = torch.tensor([1, 2, 3, 4, 5])
torch.save(xt, 'data/xt.pt')

In [9]:
# load
torch.load('data/xt.pt')

tensor([1, 2, 3, 4, 5])

## (4) Pointwise

In [10]:
# abs: absolute value of each element
torch.abs(torch.tensor([1, -3]))

tensor([1, 3])

In [11]:
# pow: the power of each element
xt = torch.tensor([1, 2, 3])
torch.pow(xt, 2)

tensor([1, 4, 9])

In [12]:
torch.pow(xt, torch.tensor([2, 1, 3]))

tensor([ 1,  2, 27])

In [13]:
# exp and log: exponential and natural logarithm
xt = torch.tensor([1, 2])
torch.exp(xt)

tensor([2.7183, 7.3891])

In [14]:
torch.log(xt)

tensor([0.0000, 0.6931])

In [15]:
torch.exp(torch.log(xt))

tensor([1., 2.])

In [16]:
# floor: retrn a new tensor with the floor of an element 
xt =  torch.randn(3)
xt

tensor([-0.7002, -0.1261, -0.8444])

In [17]:
torch.floor(xt)

tensor([-1., -1., -1.])

In [18]:
# mul: multiplies inpput by other
xt = torch.tensor([1, 2, 3])
torch.mul(xt, 10)

tensor([10, 20, 30])

In [19]:
x1 = torch.randn(3, 1)
x2 = torch.randn(1, 3)
torch.mul(x1, x2)

tensor([[ 0.0285, -0.0194, -0.1103],
        [-0.2418,  0.1646,  0.9361],
        [ 0.0396, -0.0269, -0.1531]])

##  (5) BLAS and LAPACK

In [20]:
# bmm: batch matrix-matrix product of matrices stored in input and mat2
# input and mat2 must be 3-D tensors each containing the same number of matrices.
# If input is (b × n × m) tensor, mat2 is (b × m × p) tensor, out is (b × n × p) tensor.
input1 = torch.randn(5, 3, 2)
mat2 = torch.randn(5, 2, 4)
res = torch.bmm(input1, mat2)
res.shape

torch.Size([5, 3, 4])

In [21]:
# dot: computes the dot product of two 1D tensors
torch.dot(torch.tensor([1, 2]), torch.tensor([1, 2]))

tensor(5)

In [22]:
# linalg.inv: Computes the inverse of a square matrix if it exists
A = torch.randn(2, 2)
torch.linalg.inv(A)


tensor([[-0.0426, -0.8654],
        [-0.3517,  0.3086]])

In [23]:
# linalg.det: Computes the determinant of a square matrix 
A = torch.randn(3, 3)
torch.linalg.det(A)


tensor(-3.9586)

In [24]:
# matmul: matrix product of two tensors, behavior depend on dimensionality of inputs
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([3])

In [25]:
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [26]:
# mm: matrix multiplication of the matrices input and mat2, not bradcast
mat1 = torch.randn(1, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

tensor([[-0.8420,  3.5031,  3.9178]])

In [27]:
# linalg.solve: Computes the solution of a square system of linear equations with a unique solution
A = torch.randn(2, 2)
b = torch.randn(2)
torch.linalg.solve(A, b)


tensor([ 1.4471, -1.5086])