# Introduction to tensors with Pytorch 
[Ricardo Flores](https://rflores.cl/)

In [1]:
import torch
import numpy as np 

Tensors: Multidimensional arrays

## 1) Create tensors

### Fom a list 

In [2]:
x_list = [1, 2, 3, 4, 5]
tensor_list = torch.tensor(x_list)
tensor_list

tensor([1, 2, 3, 4, 5])

### From a numpy array

In [3]:
x_array = np.array([[1, 2], [3, 4]])
tensor_np = torch.tensor(x_array)
tensor_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### From pytorch funcions

In [4]:
# Random from standar normal distribution
tensor_rand = torch.rand((3, 3))
tensor_rand

tensor([[0.6788, 0.4762, 0.6212],
        [0.6765, 0.9900, 0.5003],
        [0.5738, 0.4602, 0.4549]])

In [5]:
# Tensors of ones
tensor_ones = torch.ones((1, 3))
tensor_ones

tensor([[1., 1., 1.]])

In [6]:
# Tenzor of zeros
tensor_zeros = torch.zeros((3, 1))
tensor_zeros

tensor([[0.],
        [0.],
        [0.]])

In [7]:
# Tensor with ones on the diagonal and zeros elsewhere
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

## 2) Shape and reshape tensors 

### Check the shape of a tensor

In [8]:
# using shape
tensor_np.shape

torch.Size([2, 2])

In [9]:
# using size
tensor_np.size()

torch.Size([2, 2])

### Reshape a tensor 

In [10]:
# using reshape
tensor_np.reshape((1, 4))   # original [2, 2], then [1, 4]

tensor([[1, 2, 3, 4]], dtype=torch.int32)

In [11]:
# using view
tensor_np.view((1, 4))   # original [2, 2], then [1, 4]

tensor([[1, 2, 3, 4]], dtype=torch.int32)

### Adding  or reducing dimension

In [12]:
tensor_list.shape

torch.Size([5])

In [13]:
# adding 1 dimensiont squ
tensor_list.unsqueeze(0).shape # adding a dimention to the beginning 

torch.Size([1, 5])

In [14]:
tensor_list.unsqueeze(-1).shape # adding a dimention to the end

torch.Size([5, 1])

In [15]:
# with view
tensor_list.view(-1, 5).shape #adding a dimention to the beginning 

torch.Size([1, 5])

In [16]:
tensor_list.view(5, -1).shape # adding a dimention to the end

torch.Size([5, 1])

In [17]:
# reducing to one dimention
tensor_np.view(-1).shape

torch.Size([4])

## 3) Type of numerical data tensor 

- torch.float32 or torch.float: 32-bit floating-point
- torch.float64 or torch.double: 64-bit, double-precision floating-point
- torch.float16 or torch.half: 16-bit, half-precision floating-point
- torch.int8: signed 8-bit integers
- torch.uint8: unsigned 8-bit integers
- torch.int16 or torch.short: signed 16-bit integers
- torch.int32 or torch.int: signed 32-bit integers
- torch.int64 or torch.long: signed 64-bit integers
- torch.bool: Boolean

### Get the type of tensor

In [18]:
# print the type of tensor short(int16), int(int32), long(int64), bool
tensor_list.dtype

torch.int64

In [19]:
# float(float32), double(float64), half(float16)
tensor_rand.dtype

torch.float32

### Set new type 

In [20]:
# from int to float
tensor_list.to(torch.float).dtype

torch.float32

In [21]:
# from float to int 
tensor_ones.to(torch.int)

tensor([[1, 1, 1]], dtype=torch.int32)

## 4) Indexing tensors

In [22]:
# Same indexing that numpy
tensor_rand

tensor([[0.6788, 0.4762, 0.6212],
        [0.6765, 0.9900, 0.5003],
        [0.5738, 0.4602, 0.4549]])

In [23]:
# First column, all rows
tensor_rand[:,0]


tensor([0.6788, 0.6765, 0.5738])

In [24]:
# First two columns, all rows
tensor_rand[:,0:2]

tensor([[0.6788, 0.4762],
        [0.6765, 0.9900],
        [0.5738, 0.4602]])

In [25]:
# last row, all columns
tensor_rand[-1,:]

tensor([0.5738, 0.4602, 0.4549])

In [26]:
# last row, las column
tensor_rand[-1,-1]

tensor(0.4549)